### ISSUE TITLE
Remote charts: helm-deploy does more than helm-template

### ISSUE THREAD

**Issue by geojaz** [FairwindsOps/rok8s-scripts#253]
helm-template ignores the remote charts, while helm-deploy dutifully installs them. I would love to see helm-template grow to incorporate this functionality. I wonder if you could helm fetch the remote repos, do some templating, and then trash 'em. For those of us who have security teams that are not tiller-friendly.

**Comment by bobby-brennan** [comment]
I can take a stab at this, I did something similar for another repo. Helm 3 will work much better with remote charts, but there are workarounds for now.

**Comment by sudermanjr** [comment]
I believe this was fixed in #266.  Can you confirm @bobby-brennan ?

**Comment by bobby-brennan** [comment]
Yup, fixed in #266. Closing this
