### ISSUE TITLE
Documentation unclear on using multiple values/secrets files

### ISSUE THREAD

**Issue by jeisen** [FairwindsOps/rok8s-scripts#311]
The documentation is ambiguous and inconsistent about how to use multiple yml files in an environment. For example, I have set up a project in which I want different values depending on the region I'm deploying to, but a large amount of shared values. I created the following structure:

```
deploy
├── build.config
├── charts
│   └── my-app
├── production
│   ├── my-app-central.secret.sops.yml
│   ├── my-app-central.values.yml
│   ├── my-app-east.secret.sops.yml
│   ├── my-app-east.values.yml
│   ├── my-app-global.secret.sops.yml
│   └── my-app-global.values.yml
├── production_central.config
├── production_east.config
```

It took a lot of experimentation to determine that the correct format of the rok8s config file would be:

```
NAMESPACE='production'

SOPS_GCP_KMS_ID='path-to-sops-key'
SOPS_SECRETS=('production/my-app-global production/my-app-central')
HELM_CHARTS=('charts/my-app')
HELM_RELEASE_NAMES=('my-app-production')
HELM_VALUES=('production/my-app-global,production/my-app-central')
```

Specifically, it was confusing that `HELM_VALUES` wanted a single string of a comma-separated list, whereas `SOPS_SECRETS` wanted a space-separated list. Even attempting to debug using `helm-template` was unhelpful, since it would just exit without printing anything if I had commas in the `SOPS_SECRETS` value.

**Comment by sudermanjr** [comment]
Thanks for the issue!

I agree, the documentation is definitely a little thin in places, and it can be tough to get that format correct.  We have another issue https://github.com/FairwindsOps/rok8s-scripts/issues/275 to update docs and expand them.  I will make sure this gets added to the list of things to fix.
