### ISSUE TITLE
Document Use of non-standard docker tagging

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/rok8s-scripts#317]
https://github.com/FairwindsOps/rok8s-scripts/blob/master/bin/docker-push#L27

This var allows you to override the base set of docker tags your build creates and pushes and this should be documented. 

Notes:
It is sufficient to add 
`DOCKER_TAG_VERSIONS=( "tag" "tag" "tag" )` in the `build.config` but must keep in mind what environment variables will be available when. The build config is sourced early in the process, before some of the native `rok8s-scripts` added env vars are. Things like `$CI_SHA1`,  `$CI_REF` `$BUILD_TAG_PREFIX$CI_BUILD_NUM` will not be available without modification of the `docker_push` script.

**Comment by sudermanjr** [comment]
> Things like `$CI_SHA1`, `$CI_REF` `$BUILD_TAG_PREFIX$CI_BUILD_NUM` will not be available without modification of the `docker_push` script.

How hard do you think it would be to make that modification? I think it would be a really nice feature to have, especially if people are doing multi-arch builds and things like that

**Comment by ejether** [comment]
It would require that we reorder the individual scripts so that the helper vars are defined before the `read_config` step happens. It sounds simple on the surface but given the lack of testing in general it could be quite risky. 

So. easy to make the modification but scary.

**Comment by ejether** [comment]
This block is used in `docker-push` and `helm-deploy`
It could be moved into it's own function or script and then called _before_ `. k8s-read-config "$@"` but I don't have a good sense of what the potential side-effects would be.
```
# Set a CI_REF from branch or tag
CI_REF="${CI_TAG}"
CI_REF="${CI_REF:-$CI_BRANCH}"

if [ -z "$CI_REF" ]; then echo CI_BRANCH or CI_TAG must be set; exit 1; fi

CI_REF=$(echo "${CI_REF}" | tr / _)

# support list of tag versions
BUILD_TAG_PREFIX=${BUILD_TAG_PREFIX:-build_}
```

**Comment by sudermanjr** [comment]
Do we want to make the implementation and testing of that into its own issue so that we can prioritize that work appropriately? 

I think it makes sense to document the current state as-is and then plan to make changes later.

**Comment by ejether** [comment]
Yes, that sounds reasonable
