### ISSUE TITLE
Invalid docker tag

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/rok8s-scripts#324]
Not sure if this is due to the `+`, the length, or just a quirk of ECR, but we're seeing this message (some identifying info removed):

```
"000000000000.dkr.ecr.us-east-1.amazonaws.com/xxxxxxxxxxxxxxxxxx:dependabot_go_modules_github.com_xxxxxxxxxxxxxxxxxxxx-0.0.0+incompatible" is not a valid repository/tag
```
Should we be sanitizing tag/branch names?

**Comment by sudermanjr** [comment]
I'm gonna need a little bit more context on this one. What rok8s command are you using? What version? What does your config look like?

**Comment by rbren** [comment]
This is with the commands
```
docker-pull
docker-build
docker-push
```

Using the rok8s-scripts orb `fairwinds/rok8s-scripts@10.1`

here's the config:

```
DOCKERFILE='Dockerfile'

EXTERNAL_REGISTRY_BASE_DOMAIN=000000000000.dkr.ecr.us-east-1.amazonaws.com
REPOSITORY_NAME=xxxxxxxxxxxxxxxxxx
DOCKERTAG=${EXTERNAL_REGISTRY_BASE_DOMAIN}/${REPOSITORY_NAME}
if [[ -n $CI_TAG ]]; then
  ADDITIONAL_DOCKER_TAG_VERSIONS=()
  ADDITIONAL_DOCKER_TAG_VERSIONS+=(`echo $CI_TAG | sed -e 's/\(\w\+\)\..*$/\1/'`)
  ADDITIONAL_DOCKER_TAG_VERSIONS+=(`echo $CI_TAG | sed -e 's/\(\w\+\.\w\+\)\..*$/\1/'`)
fi
```

Confirmed the `+` is not allowed in docker tags.

**Comment by sudermanjr** [comment]
> Confirmed the `+` is not allowed in docker tags.

Thanks for confirming. Not entirely sure what the issue is here. I think f you are specifying your own tag using ADDITIONAL_DOCKER_TAG_VERSIONS then it is up to use to sanitize (like you have been doing.)

We do sanitize branch names a little but, but I'm not sure we included `+`.  That might be something we should consider adding.

**Comment by rbren** [comment]
There's no tag on this push (i.e. `CI_TAG` is unset`) so it's just coming from the branch name.

We do have `SANITIZED_BRANCH` in rok8s-scripts, which changes all non-alnum chars to `-`. But it looks like `docker-push` uses `$CI_BRANCH` instead:

https://github.com/FairwindsOps/rok8s-scripts/blob/master/bin/docker-push#L17

**Comment by sudermanjr** [comment]
Oh weird. I could have sworn we were doing something different there. I will mark this as a bug and take a look at it.
